package br.com.expenseController.controllers;


/**
* br/com/expenseController/controllers/PeriodControllerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../expenseController.idl
* Terça-feira, 5 de Novembro de 2019 00h24min46s BRST
*/

public abstract class PeriodControllerPOA extends org.omg.PortableServer.Servant
 implements br.com.expenseController.controllers.PeriodControllerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insert", new java.lang.Integer (0));
    _methods.put ("update", new java.lang.Integer (1));
    _methods.put ("remove", new java.lang.Integer (2));
    _methods.put ("load", new java.lang.Integer (3));
    _methods.put ("loadAll", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/com/expenseController/controllers/PeriodController/insert
       {
         br.com.expenseController.Period period = br.com.expenseController.PeriodHelper.read (in);
         boolean $result = false;
         $result = this.insert (period);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // br/com/expenseController/controllers/PeriodController/update
       {
         br.com.expenseController.Period period = br.com.expenseController.PeriodHelper.read (in);
         boolean $result = false;
         $result = this.update (period);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // br/com/expenseController/controllers/PeriodController/remove
       {
         br.com.expenseController.Period period = br.com.expenseController.PeriodHelper.read (in);
         boolean $result = false;
         $result = this.remove (period);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // br/com/expenseController/controllers/PeriodController/load
       {
         int code = in.read_long ();
         br.com.expenseController.Period $result = null;
         $result = this.load (code);
         out = $rh.createReply();
         br.com.expenseController.PeriodHelper.write (out, $result);
         break;
       }

       case 4:  // br/com/expenseController/controllers/PeriodController/loadAll
       {
         br.com.expenseController.Period $result[] = null;
         $result = this.loadAll ();
         out = $rh.createReply();
         br.com.expenseController.PeriodsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/com/expenseController/controllers/PeriodController:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PeriodController _this() 
  {
    return PeriodControllerHelper.narrow(
    super._this_object());
  }

  public PeriodController _this(org.omg.CORBA.ORB orb) 
  {
    return PeriodControllerHelper.narrow(
    super._this_object(orb));
  }


} // class PeriodControllerPOA
